//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABO.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABO.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chấm dứt thực thi.
        /// </summary>
        internal static string AlertifyDialog_Canceled {
            get {
                return ResourceManager.GetString("AlertifyDialog.Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tiếp tục xử lý.
        /// </summary>
        internal static string AlertifyDialog_Confirmed {
            get {
                return ResourceManager.GetString("AlertifyDialog.Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string AlertifyDialog_ConfirmTitle {
            get {
                return ResourceManager.GetString("AlertifyDialog.ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        internal static string Common_All {
            get {
                return ResourceManager.GetString("Common.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABO System.
        /// </summary>
        internal static string Common_AppDescription {
            get {
                return ResourceManager.GetString("Common.AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABO.
        /// </summary>
        internal static string Common_AppFullName {
            get {
                return ResourceManager.GetString("Common.AppFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABO.
        /// </summary>
        internal static string Common_AppName {
            get {
                return ResourceManager.GetString("Common.AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu.
        /// </summary>
        internal static string Common_Begin {
            get {
                return ResourceManager.GetString("Common.Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2014 - Bản quyền thuộc về ABO.
        /// </summary>
        internal static string Common_Copyright {
            get {
                return ResourceManager.GetString("Common.Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string Common_Edit {
            get {
                return ResourceManager.GetString("Common.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất ra Excel.
        /// </summary>
        internal static string Common_Excel {
            get {
                return ResourceManager.GetString("Common.Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý.
        /// </summary>
        internal static string Common_Execute {
            get {
                return ResourceManager.GetString("Common.Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        internal static string Common_Hello {
            get {
                return ResourceManager.GetString("Common.Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập vào.
        /// </summary>
        internal static string Common_Import {
            get {
                return ResourceManager.GetString("Common.Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu..
        /// </summary>
        internal static string Common_Message_NoRecordFound {
            get {
                return ResourceManager.GetString("Common.Message.NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        internal static string Common_Page {
            get {
                return ResourceManager.GetString("Common.Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        internal static string Common_Page_Display {
            get {
                return ResourceManager.GetString("Common.Page.Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang đầu.
        /// </summary>
        internal static string Common_Page_First {
            get {
                return ResourceManager.GetString("Common.Page.First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kết quả.
        /// </summary>
        internal static string Common_Page_FoundRecords {
            get {
                return ResourceManager.GetString("Common.Page.FoundRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Common_Page_Go {
            get {
                return ResourceManager.GetString("Common.Page.Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển trang.
        /// </summary>
        internal static string Common_Page_Go_Hint {
            get {
                return ResourceManager.GetString("Common.Page.Go.Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang cuối.
        /// </summary>
        internal static string Common_Page_Last {
            get {
                return ResourceManager.GetString("Common.Page.Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang sau.
        /// </summary>
        internal static string Common_Page_Next {
            get {
                return ResourceManager.GetString("Common.Page.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang trước.
        /// </summary>
        internal static string Common_Page_Previous {
            get {
                return ResourceManager.GetString("Common.Page.Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy KQ.
        /// </summary>
        internal static string Common_ResetSearch {
            get {
                return ResourceManager.GetString("Common.ResetSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy kết quả đã tìm.
        /// </summary>
        internal static string Common_ResetSearch_Hint {
            get {
                return ResourceManager.GetString("Common.ResetSearch.Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        internal static string Common_Search {
            get {
                return ResourceManager.GetString("Common.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        internal static string Common_StartDate {
            get {
                return ResourceManager.GetString("Common.StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được quá {1} ký tự..
        /// </summary>
        internal static string Common_Validation_StringMaxLength {
            get {
                return ResourceManager.GetString("Common.Validation.StringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thật sự muốn xóa Đợt xóa dữ liệu này không?.
        /// </summary>
        internal static string DataPurge_ConfirmDeletePurge {
            get {
                return ResourceManager.GetString("DataPurge.ConfirmDeletePurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi khi xóa Đợt xóa dữ liệu. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string DataPurge_FailedToDeletePurge {
            get {
                return ResourceManager.GetString("DataPurge.FailedToDeletePurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi khi đăng ký. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string DataPurge_FailedToRegister {
            get {
                return ResourceManager.GetString("DataPurge.FailedToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        internal static string DataPurge_Field_EndDate {
            get {
                return ResourceManager.GetString("DataPurge.Field.EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chạy.
        /// </summary>
        internal static string DataPurge_Field_PurgeDate {
            get {
                return ResourceManager.GetString("DataPurge.Field.PurgeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa HS từ ngày.
        /// </summary>
        internal static string DataPurge_Field_StartDate {
            get {
                return ResourceManager.GetString("DataPurge.Field.StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        internal static string DataPurge_Grid_EndDate {
            get {
                return ResourceManager.GetString("DataPurge.Grid.EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL file.
        /// </summary>
        internal static string DataPurge_Grid_FileCount {
            get {
                return ResourceManager.GetString("DataPurge.Grid.FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đợt xóa dữ liệu.
        /// </summary>
        internal static string DataPurge_Grid_PurgeDate {
            get {
                return ResourceManager.GetString("DataPurge.Grid.PurgeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa những HS có status Đã xóa từ ngày.
        /// </summary>
        internal static string DataPurge_Grid_StartDate {
            get {
                return ResourceManager.GetString("DataPurge.Grid.StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string DataPurge_Grid_UserName {
            get {
                return ResourceManager.GetString("DataPurge.Grid.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string DataPurge_Register {
            get {
                return ResourceManager.GetString("DataPurge.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký đợt xóa định kì.
        /// </summary>
        internal static string DataPurge_RegisterDataPurge {
            get {
                return ResourceManager.GetString("DataPurge.RegisterDataPurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Đợt xóa dữ liệu thành công!.
        /// </summary>
        internal static string DataPurge_SuccessToDeletePurge {
            get {
                return ResourceManager.GetString("DataPurge.SuccessToDeletePurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký đợt xóa định kì thành công..
        /// </summary>
        internal static string DataPurge_SuccessToRegister {
            get {
                return ResourceManager.GetString("DataPurge.SuccessToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên NPP.
        /// </summary>
        internal static string Distributor_NotScanned_DistName {
            get {
                return ResourceManager.GetString("Distributor.NotScanned.DistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPP.
        /// </summary>
        internal static string Distributor_NotScanned_DistNumber {
            get {
                return ResourceManager.GetString("Distributor.NotScanned.DistNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        internal static string Distributor_NotScanned_ExpiryDate {
            get {
                return ResourceManager.GetString("Distributor.NotScanned.ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất ra Excel.
        /// </summary>
        internal static string Distributor_NotScanned_ExportToExcel {
            get {
                return ResourceManager.GetString("Distributor.NotScanned.ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày gia nhập.
        /// </summary>
        internal static string Distributor_NotScanned_JoinDate {
            get {
                return ResourceManager.GetString("Distributor.NotScanned.JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thay đổi.
        /// </summary>
        internal static string Distributor_NotScanned_UpdatedDate {
            get {
                return ResourceManager.GetString("Distributor.NotScanned.UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi.
        /// </summary>
        internal static string Distributor_NotScanned_UpdatedType {
            get {
                return ResourceManager.GetString("Distributor.NotScanned.UpdatedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thay đổi.
        /// </summary>
        internal static string Distributor_NotScanned_UpdateType {
            get {
                return ResourceManager.GetString("Distributor.NotScanned.UpdateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        internal static string Distributor_NotScanned_WarehouseId {
            get {
                return ResourceManager.GetString("Distributor.NotScanned.WarehouseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string DistributorLetter_AddNew {
            get {
                return ResourceManager.GetString("DistributorLetter.AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xuất thư.
        /// </summary>
        internal static string DistributorLetter_LetterDate {
            get {
                return ResourceManager.GetString("DistributorLetter.LetterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS mới.
        /// </summary>
        internal static string DistributorLetter_NewDistNum {
            get {
                return ResourceManager.GetString("DistributorLetter.NewDistNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà phân phối mới.
        /// </summary>
        internal static string DistributorLetter_NewDistributor {
            get {
                return ResourceManager.GetString("DistributorLetter.NewDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS cũ.
        /// </summary>
        internal static string DistributorLetter_OldDistNum {
            get {
                return ResourceManager.GetString("DistributorLetter.OldDistNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người bảo trợ trực tiếp Platium nhánh cũ.
        /// </summary>
        internal static string DistributorLetter_OldPlatium {
            get {
                return ResourceManager.GetString("DistributorLetter.OldPlatium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người bảo trợ trực tiếp nhánh cũ.
        /// </summary>
        internal static string DistributorLetter_OldSponsor {
            get {
                return ResourceManager.GetString("DistributorLetter.OldSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        internal static string DistributorLetter_Warehouse {
            get {
                return ResourceManager.GetString("DistributorLetter.Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa.
        /// </summary>
        internal static string Enums_AssetStatus_Deleted {
            get {
                return ResourceManager.GetString("Enums.AssetStatus.Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết sử dụng.
        /// </summary>
        internal static string Enums_AssetStatus_Expired {
            get {
                return ResourceManager.GetString("Enums.AssetStatus.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang sử dụng.
        /// </summary>
        internal static string Enums_AssetStatus_InUsed {
            get {
                return ResourceManager.GetString("Enums.AssetStatus.InUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang sử dụng (có lỗi).
        /// </summary>
        internal static string Enums_AssetStatus_InUsedFault {
            get {
                return ResourceManager.GetString("Enums.AssetStatus.InUsedFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới phát hiện.
        /// </summary>
        internal static string Enums_AssetStatus_New {
            get {
                return ResourceManager.GetString("Enums.AssetStatus.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy.
        /// </summary>
        internal static string Enums_AssetStatus_NotFound {
            get {
                return ResourceManager.GetString("Enums.AssetStatus.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kiểm tra.
        /// </summary>
        internal static string Enums_InventoryDetailStatus_Invalidated {
            get {
                return ResourceManager.GetString("Enums.InventoryDetailStatus.Invalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển từ nơi khác đến.
        /// </summary>
        internal static string Enums_InventoryDetailStatus_Moved {
            get {
                return ResourceManager.GetString("Enums.InventoryDetailStatus.Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới phát hiện.
        /// </summary>
        internal static string Enums_InventoryDetailStatus_New {
            get {
                return ResourceManager.GetString("Enums.InventoryDetailStatus.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã kiểm tra.
        /// </summary>
        internal static string Enums_InventoryDetailStatus_Validated {
            get {
                return ResourceManager.GetString("Enums.InventoryDetailStatus.Validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn Tất.
        /// </summary>
        internal static string Enums_InventoryStatus_Completed {
            get {
                return ResourceManager.GetString("Enums.InventoryStatus.Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang Tiến Hành.
        /// </summary>
        internal static string Enums_InventoryStatus_InProgress {
            get {
                return ResourceManager.GetString("Enums.InventoryStatus.InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có thể hủy.
        /// </summary>
        internal static string Enums_ProfileBoxStatus_Discardable {
            get {
                return ResourceManager.GetString("Enums.ProfileBoxStatus.Discardable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hủy.
        /// </summary>
        internal static string Enums_ProfileBoxStatus_Discarded {
            get {
                return ResourceManager.GetString("Enums.ProfileBoxStatus.Discarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chuyển đi.
        /// </summary>
        internal static string Enums_ProfileBoxStatus_Moved {
            get {
                return ResourceManager.GetString("Enums.ProfileBoxStatus.Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần hủy.
        /// </summary>
        internal static string Enums_ProfileBoxStatus_NeedToDiscard {
            get {
                return ResourceManager.GetString("Enums.ProfileBoxStatus.NeedToDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang Mở.
        /// </summary>
        internal static string Enums_ProfileBoxStatus_Open {
            get {
                return ResourceManager.GetString("Enums.ProfileBoxStatus.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đóng gói.
        /// </summary>
        internal static string Enums_ProfileBoxStatus_Packed {
            get {
                return ResourceManager.GetString("Enums.ProfileBoxStatus.Packed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu Kho.
        /// </summary>
        internal static string Enums_ProfileBoxStatus_Stored {
            get {
                return ResourceManager.GetString("Enums.ProfileBoxStatus.Stored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa.
        /// </summary>
        internal static string Enums_ProfileStatus_Deleted {
            get {
                return ResourceManager.GetString("Enums.ProfileStatus.Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần xóa.
        /// </summary>
        internal static string Enums_ProfileStatus_NeedToDelete {
            get {
                return ResourceManager.GetString("Enums.ProfileStatus.NeedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu Lực.
        /// </summary>
        internal static string Enums_ProfileStatus_Valid {
            get {
                return ResourceManager.GetString("Enums.ProfileStatus.Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập trang này!.
        /// </summary>
        internal static string Error_Forbidden_Description {
            get {
                return ResourceManager.GetString("Error.Forbidden.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền.
        /// </summary>
        internal static string Error_Forbidden_PageTitle {
            get {
                return ResourceManager.GetString("Error.Forbidden.PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang web không tồn tại. Vui lòng thử lại đường dẫn khác!.
        /// </summary>
        internal static string Error_NotFound_Description {
            get {
                return ResourceManager.GetString("Error.NotFound.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy.
        /// </summary>
        internal static string Error_NotFound_PageTitle {
            get {
                return ResourceManager.GetString("Error.NotFound.PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra trong hệ thống. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string Error_ServerError_Description {
            get {
                return ResourceManager.GetString("Error.ServerError.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống.
        /// </summary>
        internal static string Error_ServerError_PageTitle {
            get {
                return ResourceManager.GetString("Error.ServerError.PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dành cho DR.
        /// </summary>
        internal static string Help_ForDR {
            get {
                return ResourceManager.GetString("Help.ForDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dành cho DR Leader.
        /// </summary>
        internal static string Help_ForDRLeader {
            get {
                return ResourceManager.GetString("Help.ForDRLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dành cho Khách.
        /// </summary>
        internal static string Help_ForGuess {
            get {
                return ResourceManager.GetString("Help.ForGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn 1 link từ menu bên trên để bắt đầu sử dụng các năng trong hệ thống..
        /// </summary>
        internal static string Home_Guidelines {
            get {
                return ResourceManager.GetString("Home.Guidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng bạn đến với ABO!.
        /// </summary>
        internal static string HomePage_WelcomeMessage {
            get {
                return ResourceManager.GetString("HomePage.WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu tài sản mới không thành công. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string Inventory_AssetRecord_Individual_Failed {
            get {
                return ResourceManager.GetString("Inventory.AssetRecord.Individual.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài sản mới đã được lưu thành công..
        /// </summary>
        internal static string Inventory_AssetRecord_Individual_Success {
            get {
                return ResourceManager.GetString("Inventory.AssetRecord.Individual.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra trong quá trình nhập file. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string Inventory_AssetRecord_List_FailedToImport {
            get {
                return ResourceManager.GetString("Inventory.AssetRecord.List.FailedToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đã chọn không hợp lệ..
        /// </summary>
        internal static string Inventory_AssetRecord_List_InvalidFile {
            get {
                return ResourceManager.GetString("Inventory.AssetRecord.List.InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHÚ Ý: Những tài sản có mã sau đây không tìm thấy trong hệ thống: {0}..
        /// </summary>
        internal static string Inventory_AssetRecord_List_NotFoundAssetWarning {
            get {
                return ResourceManager.GetString("Inventory.AssetRecord.List.NotFoundAssetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;Danh sách đã kiểm&quot; chưa được chọn..
        /// </summary>
        internal static string Inventory_AssetRecord_List_SelectFile {
            get {
                return ResourceManager.GetString("Inventory.AssetRecord.List.SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đã được nhập thành công..
        /// </summary>
        internal static string Inventory_AssetRecord_List_SuccessToImport {
            get {
                return ResourceManager.GetString("Inventory.AssetRecord.List.SuccessToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người kiểm kê.
        /// </summary>
        internal static string Inventory_Checker {
            get {
                return ResourceManager.GetString("Inventory.Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu.
        /// </summary>
        internal static string Menu_DataPurge {
            get {
                return ResourceManager.GetString("Menu.DataPurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà phân phối.
        /// </summary>
        internal static string Menu_Distributor {
            get {
                return ResourceManager.GetString("Menu.Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn sử dụng.
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPP chưa được scan.
        /// </summary>
        internal static string Menu_NotScannedDistributor {
            get {
                return ResourceManager.GetString("Menu.NotScannedDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In thư tái gia nhập.
        /// </summary>
        internal static string Menu_PrintLetter {
            get {
                return ResourceManager.GetString("Menu.PrintLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ của NPP.
        /// </summary>
        internal static string Menu_Profile {
            get {
                return ResourceManager.GetString("Menu.Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thùng hồ sơ.
        /// </summary>
        internal static string Menu_ProfileBox {
            get {
                return ResourceManager.GetString("Menu.ProfileBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ.
        /// </summary>
        internal static string Menu_ProfileGroup {
            get {
                return ResourceManager.GetString("Menu.ProfileGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gắn hình vào hợp đồng.
        /// </summary>
        internal static string Menu_ProfileImageMerging {
            get {
                return ResourceManager.GetString("Menu.ProfileImageMerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả xử lý hàng ngày.
        /// </summary>
        internal static string Menu_ProfileScan {
            get {
                return ResourceManager.GetString("Menu.ProfileScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hồ sơ.
        /// </summary>
        internal static string Menu_ProfileType {
            get {
                return ResourceManager.GetString("Menu.ProfileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Menu_User {
            get {
                return ResourceManager.GetString("Menu.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đ/c.
        /// </summary>
        internal static string NewLetter_Address {
            get {
                return ResourceManager.GetString("NewLetter.Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        internal static string NewLetter_Creator {
            get {
                return ResourceManager.GetString("NewLetter.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPP mới.
        /// </summary>
        internal static string NewLetter_Distributor {
            get {
                return ResourceManager.GetString("NewLetter.Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên NPP mới.
        /// </summary>
        internal static string NewLetter_DistributorName {
            get {
                return ResourceManager.GetString("NewLetter.DistributorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTTT nhánh cũ.
        /// </summary>
        internal static string NewLetter_OldDistributor {
            get {
                return ResourceManager.GetString("NewLetter.OldDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên BTTT nhánh cũ.
        /// </summary>
        internal static string NewLetter_OldDistributorName {
            get {
                return ResourceManager.GetString("NewLetter.OldDistributorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTTT Nhánh.
        /// </summary>
        internal static string NewLetter_Sponsor {
            get {
                return ResourceManager.GetString("NewLetter.Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên BTTT nhánh.
        /// </summary>
        internal static string NewLetter_SponsorName {
            get {
                return ResourceManager.GetString("NewLetter.SponsorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT (Mobile).
        /// </summary>
        internal static string NewLetter_Telephone {
            get {
                return ResourceManager.GetString("NewLetter.Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi Nhánh.
        /// </summary>
        internal static string NewLetter_Warehouse {
            get {
                return ResourceManager.GetString("NewLetter.Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTTT cấp.
        /// </summary>
        internal static string NewLettter_Platium {
            get {
                return ResourceManager.GetString("NewLettter.Platium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên BTTT cấp.
        /// </summary>
        internal static string NewLettter_PlatiumName {
            get {
                return ResourceManager.GetString("NewLettter.PlatiumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết tài sản.
        /// </summary>
        internal static string PageTitle_AssetDetails {
            get {
                return ResourceManager.GetString("PageTitle.AssetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng đợt kiểm kê.
        /// </summary>
        internal static string PageTitle_CloseInventory {
            get {
                return ResourceManager.GetString("PageTitle.CloseInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả xử lý hàng ngày.
        /// </summary>
        internal static string PageTitle_DailyScanResult {
            get {
                return ResourceManager.GetString("PageTitle.DailyScanResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu định kì.
        /// </summary>
        internal static string PageTitle_DataPurge {
            get {
                return ResourceManager.GetString("PageTitle.DataPurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn sử dụng.
        /// </summary>
        internal static string PageTitle_Help {
            get {
                return ResourceManager.GetString("PageTitle.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string PageTitle_Home {
            get {
                return ResourceManager.GetString("PageTitle.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm kê.
        /// </summary>
        internal static string PageTitle_Inventory {
            get {
                return ResourceManager.GetString("PageTitle.Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết đợt kiểm kê.
        /// </summary>
        internal static string PageTitle_InventoryDetails {
            get {
                return ResourceManager.GetString("PageTitle.InventoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đợt kiểm kê.
        /// </summary>
        internal static string PageTitle_ListOfInventory {
            get {
                return ResourceManager.GetString("PageTitle.ListOfInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPP có thay đổi nhưng chưa có thông tin trên hệ thống.
        /// </summary>
        internal static string PageTitle_NotScannedDistributorUpdates {
            get {
                return ResourceManager.GetString("PageTitle.NotScannedDistributorUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở đợt kiểm kê.
        /// </summary>
        internal static string PageTitle_OpenInventory {
            get {
                return ResourceManager.GetString("PageTitle.OpenInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In thư tái gia nhập.
        /// </summary>
        internal static string PageTitle_PrintLetter {
            get {
                return ResourceManager.GetString("PageTitle.PrintLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HS của từng NPP.
        /// </summary>
        internal static string PageTitle_Profile {
            get {
                return ResourceManager.GetString("PageTitle.Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thùng HS.
        /// </summary>
        internal static string PageTitle_ProfileBox {
            get {
                return ResourceManager.GetString("PageTitle.ProfileBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chèn ảnh vào hồ sơ.
        /// </summary>
        internal static string PageTitle_ProfileImageMerging {
            get {
                return ResourceManager.GetString("PageTitle.ProfileImageMerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách loại HS.
        /// </summary>
        internal static string PageTitle_ProfileType {
            get {
                return ResourceManager.GetString("PageTitle.ProfileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhận tài sản.
        /// </summary>
        internal static string PageTitle_RecordAssets {
            get {
                return ResourceManager.GetString("PageTitle.RecordAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách user.
        /// </summary>
        internal static string PageTitle_User {
            get {
                return ResourceManager.GetString("PageTitle.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ADA mới không tồn tại trong hệ thống!.
        /// </summary>
        internal static string Profile_ChangeADA_NewADANotFound {
            get {
                return ResourceManager.GetString("Profile.ChangeADA.NewADANotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi ADA.
        /// </summary>
        internal static string Profile_ChangeADA_Title {
            get {
                return ResourceManager.GetString("Profile.ChangeADA.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thùng HS.
        /// </summary>
        internal static string Profile_ChangeProfileBox_Title {
            get {
                return ResourceManager.GetString("Profile.ChangeProfileBox.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thật sự muốn xóa file?.
        /// </summary>
        internal static string Profile_ConfirmDeleteProfiles {
            get {
                return ResourceManager.GetString("Profile.ConfirmDeleteProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ADA hiện tại.
        /// </summary>
        internal static string Profile_CurrentADA {
            get {
                return ResourceManager.GetString("Profile.CurrentADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string Profile_Distributor_Address {
            get {
                return ResourceManager.GetString("Profile.Distributor.Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        internal static string Profile_Distributor_ExpiryDate {
            get {
                return ResourceManager.GetString("Profile.Distributor.ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày gia nhập.
        /// </summary>
        internal static string Profile_Distributor_JoinDate {
            get {
                return ResourceManager.GetString("Profile.Distributor.JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên NPP.
        /// </summary>
        internal static string Profile_Distributor_Name {
            get {
                return ResourceManager.GetString("Profile.Distributor.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        internal static string Profile_Distributor_Warehouse {
            get {
                return ResourceManager.GetString("Profile.Distributor.Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File hồ sơ không tồn tại. Vui lòng nhấn nút &quot;Back&quot; của trình duyệt để quay về trang trước!.
        /// </summary>
        internal static string Profile_DownloadedFileNotFound {
            get {
                return ResourceManager.GetString("Profile.DownloadedFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thùng đã tồn tại. Vui lòng sử dụng tên khác.
        /// </summary>
        internal static string Profile_FailedToAddProfileBoxDulicatePath {
            get {
                return ResourceManager.GetString("Profile.FailedToAddProfileBoxDulicatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi khi thay đổi ADA. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string Profile_FailedToChangeADA {
            get {
                return ResourceManager.GetString("Profile.FailedToChangeADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thễ thực hiện tác vụ này.
        /// </summary>
        internal static string Profile_FailedToChangeStatusProfileBoxes {
            get {
                return ResourceManager.GetString("Profile.FailedToChangeStatusProfileBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hủy thùng.
        /// </summary>
        internal static string Profile_FailedToDeleteProfileBoxes {
            get {
                return ResourceManager.GetString("Profile.FailedToDeleteProfileBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi khi xóa file. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string Profile_FailedToDeleteProfiles {
            get {
                return ResourceManager.GetString("Profile.FailedToDeleteProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần quyền TeamLeader để sử dụng chức năng này. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string Profile_FailedToDiscardProfileBoxes {
            get {
                return ResourceManager.GetString("Profile.FailedToDiscardProfileBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ trong thùng phải có trạng thái đã xóa hoặc thùng không có hồ sơ nào..
        /// </summary>
        internal static string Profile_FailedToDiscardProfileBoxes2 {
            get {
                return ResourceManager.GetString("Profile.FailedToDiscardProfileBoxes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi khi xuất file PDF. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string Profile_FailedToExportPDFs {
            get {
                return ResourceManager.GetString("Profile.FailedToExportPDFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi chuyển HS.
        /// </summary>
        internal static string Profile_FailedToMoveProfile {
            get {
                return ResourceManager.GetString("Profile.FailedToMoveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần quyền TeamLeader để sử dụng chức năng này. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string Profile_FailedToMoveProfileBoxes {
            get {
                return ResourceManager.GetString("Profile.FailedToMoveProfileBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần quyền TeamLeader để sử dụng chức năng này.Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string Profile_FailedToPackagedProfileBoxes {
            get {
                return ResourceManager.GetString("Profile.FailedToPackagedProfileBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần quyền TeamLeader để sử dụng chức năng này. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string Profile_FailedToStoreProfileBoxes {
            get {
                return ResourceManager.GetString("Profile.FailedToStoreProfileBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HS của ADA.
        /// </summary>
        internal static string Profile_ID {
            get {
                return ResourceManager.GetString("Profile.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ di chuyển HS có trạng thái đang mở.
        /// </summary>
        internal static string Profile_MoveToError {
            get {
                return ResourceManager.GetString("Profile.MoveToError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số NPP.
        /// </summary>
        internal static string Profile_Name {
            get {
                return ResourceManager.GetString("Profile.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ADA mới.
        /// </summary>
        internal static string Profile_NewADA {
            get {
                return ResourceManager.GetString("Profile.NewADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thùng HS mới.
        /// </summary>
        internal static string Profile_NewProfileBox {
            get {
                return ResourceManager.GetString("Profile.NewProfileBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thùng HS.
        /// </summary>
        internal static string Profile_ProfileBox_BoxName {
            get {
                return ResourceManager.GetString("Profile.ProfileBox.BoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string Profile_ProfileBox_CreatedByUserName {
            get {
                return ResourceManager.GetString("Profile.ProfileBox.CreatedByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        internal static string Profile_ProfileBox_CreatedDate {
            get {
                return ResourceManager.GetString("Profile.ProfileBox.CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa file được chọn.
        /// </summary>
        internal static string Profile_ProfileBox_DeleteSelectedFile {
            get {
                return ResourceManager.GetString("Profile.ProfileBox.DeleteSelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string Profile_ProfileBox_Description {
            get {
                return ResourceManager.GetString("Profile.ProfileBox.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất toàn bộ ra PDF.
        /// </summary>
        internal static string Profile_ProfileBox_ExportAllToPdf {
            get {
                return ResourceManager.GetString("Profile.ProfileBox.ExportAllToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string Profile_ProfileBox_StatusName {
            get {
                return ResourceManager.GetString("Profile.ProfileBox.StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại HS.
        /// </summary>
        internal static string Profile_ProfileBox_TypeName {
            get {
                return ResourceManager.GetString("Profile.ProfileBox.TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi ADA.
        /// </summary>
        internal static string Profile_ProfileBox_UpdateADA {
            get {
                return ResourceManager.GetString("Profile.ProfileBox.UpdateADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thùng HS.
        /// </summary>
        internal static string Profile_ProfileBox_UpdateBox {
            get {
                return ResourceManager.GetString("Profile.ProfileBox.UpdateBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse ID.
        /// </summary>
        internal static string Profile_ProfileBox_WarehouseName {
            get {
                return ResourceManager.GetString("Profile.ProfileBox.WarehouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày scan.
        /// </summary>
        internal static string Profile_ScanDate {
            get {
                return ResourceManager.GetString("Profile.ScanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chỉ được chọn 1 hồ sơ để thực hiện tác vụ này!.
        /// </summary>
        internal static string Profile_SelectOneProfileOnly {
            get {
                return ResourceManager.GetString("Profile.SelectOneProfileOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn hồ sơ nào!.
        /// </summary>
        internal static string Profile_SelectProfileRequired {
            get {
                return ResourceManager.GetString("Profile.SelectProfileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng Thái HS.
        /// </summary>
        internal static string Profile_Status {
            get {
                return ResourceManager.GetString("Profile.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo thùng thành công..
        /// </summary>
        internal static string Profile_SuccessToAddProfileBox {
            get {
                return ResourceManager.GetString("Profile.SuccessToAddProfileBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi ADA thành công!.
        /// </summary>
        internal static string Profile_SuccessToChangeADA {
            get {
                return ResourceManager.GetString("Profile.SuccessToChangeADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hủy thùng.
        /// </summary>
        internal static string Profile_SuccessToDeleteProfileBoxes {
            get {
                return ResourceManager.GetString("Profile.SuccessToDeleteProfileBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File được chọn đã bị xóa..
        /// </summary>
        internal static string Profile_SuccessToDeleteProfiles {
            get {
                return ResourceManager.GetString("Profile.SuccessToDeleteProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hủy thùng.
        /// </summary>
        internal static string Profile_SuccessToDiscardProfileBoxes {
            get {
                return ResourceManager.GetString("Profile.SuccessToDiscardProfileBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HS Chuyển thành công.
        /// </summary>
        internal static string Profile_SuccessToMoveProfile {
            get {
                return ResourceManager.GetString("Profile.SuccessToMoveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chuyển thùng.
        /// </summary>
        internal static string Profile_SuccessToMoveProfileBoxes {
            get {
                return ResourceManager.GetString("Profile.SuccessToMoveProfileBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đóng gói thùng.
        /// </summary>
        internal static string Profile_SuccessToPackagedProfileBoxes {
            get {
                return ResourceManager.GetString("Profile.SuccessToPackagedProfileBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lưu kho.
        /// </summary>
        internal static string Profile_SuccessToStoreProfileBoxes {
            get {
                return ResourceManager.GetString("Profile.SuccessToStoreProfileBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách hồ sơ của bạn.
        /// </summary>
        internal static string Profile_YourUnboxedList {
            get {
                return ResourceManager.GetString("Profile.YourUnboxedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL ADA.
        /// </summary>
        internal static string ProfileBox_AdaCount {
            get {
                return ResourceManager.GetString("ProfileBox.AdaCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thùng mới.
        /// </summary>
        internal static string ProfileBox_AddNewBox {
            get {
                return ResourceManager.GetString("ProfileBox.AddNewBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái thùng.
        /// </summary>
        internal static string ProfileBox_BoxStatus {
            get {
                return ResourceManager.GetString("ProfileBox.BoxStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string ProfileBox_BoxStatus2 {
            get {
                return ResourceManager.GetString("ProfileBox.BoxStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        internal static string ProfileBox_CreatedDate {
            get {
                return ResourceManager.GetString("ProfileBox.CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo thùng.
        /// </summary>
        internal static string ProfileBox_Creator {
            get {
                return ResourceManager.GetString("ProfileBox.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết thùng HS.
        /// </summary>
        internal static string ProfileBox_Detail {
            get {
                return ResourceManager.GetString("ProfileBox.Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy Thùng.
        /// </summary>
        internal static string ProfileBox_Discard {
            get {
                return ResourceManager.GetString("ProfileBox.Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy thùng chọn.
        /// </summary>
        internal static string ProfileBox_DiscardBoxes {
            get {
                return ResourceManager.GetString("ProfileBox.DiscardBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ được hủy thùng có trạng thái cần hủy.
        /// </summary>
        internal static string ProfileBox_DiscardError {
            get {
                return ResourceManager.GetString("ProfileBox.DiscardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu file vào.
        /// </summary>
        internal static string ProfileBox_FolderPath {
            get {
                return ResourceManager.GetString("ProfileBox.FolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Label.
        /// </summary>
        internal static string ProfileBox_Label {
            get {
                return ResourceManager.GetString("ProfileBox.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí ở kho lưu.
        /// </summary>
        internal static string ProfileBox_Location {
            get {
                return ResourceManager.GetString("ProfileBox.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thùng.
        /// </summary>
        internal static string ProfileBox_Name {
            get {
                return ResourceManager.GetString("ProfileBox.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi Nhánh.
        /// </summary>
        internal static string ProfileBox_OfficeName {
            get {
                return ResourceManager.GetString("ProfileBox.OfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Thùng.
        /// </summary>
        internal static string ProfileBox_ProfileBoxName {
            get {
                return ResourceManager.GetString("ProfileBox.ProfileBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng HS.
        /// </summary>
        internal static string ProfileBox_ProfileCount {
            get {
                return ResourceManager.GetString("ProfileBox.ProfileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại HS.
        /// </summary>
        internal static string ProfileBox_ProfileType {
            get {
                return ResourceManager.GetString("ProfileBox.ProfileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cập nhật.
        /// </summary>
        internal static string ProfileBox_UpdatedDate {
            get {
                return ResourceManager.GetString("ProfileBox.UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string ProfileBox_UserID {
            get {
                return ResourceManager.GetString("ProfileBox.UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        internal static string ProfileBox_WareHouse {
            get {
                return ResourceManager.GetString("ProfileBox.WareHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu Kho.
        /// </summary>
        internal static string ProfileBox_WareHouse2 {
            get {
                return ResourceManager.GetString("ProfileBox.WareHouse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất DS HS.
        /// </summary>
        internal static string ProfileBoxDetail_ExportToExcel {
            get {
                return ResourceManager.GetString("ProfileBoxDetail.ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển các HS đã chọn sang thùng.
        /// </summary>
        internal static string ProfileBoxDetail_Moved {
            get {
                return ResourceManager.GetString("ProfileBoxDetail.Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số ADA cần lấy hồ sơ.
        /// </summary>
        internal static string ProfileImageMerging_AdaNo {
            get {
                return ResourceManager.GetString("ProfileImageMerging.AdaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hủy thao tác.
        /// </summary>
        internal static string ProfileImageMerging_Cancel {
            get {
                return ResourceManager.GetString("ProfileImageMerging.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng xác nhận.
        /// </summary>
        internal static string ProfileImageMerging_ConfirmModal {
            get {
                return ResourceManager.GetString("ProfileImageMerging.ConfirmModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy file {0} trên server. Vui lòng liên hệ admin!.
        /// </summary>
        internal static string ProfileImageMerging_ContractFileNotFound {
            get {
                return ResourceManager.GetString("ProfileImageMerging.ContractFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy NPP này!.
        /// </summary>
        internal static string ProfileImageMerging_FailedToFindDistributor {
            get {
                return ResourceManager.GetString("ProfileImageMerging.FailedToFindDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy hình ở WTA!.
        /// </summary>
        internal static string ProfileImageMerging_FailedToFindImages {
            get {
                return ResourceManager.GetString("ProfileImageMerging.FailedToFindImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ NPP này chưa được upload lên!.
        /// </summary>
        internal static string ProfileImageMerging_FailedToFindProfile {
            get {
                return ResourceManager.GetString("ProfileImageMerging.FailedToFindProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy ảnh của người đứng tên.
        /// </summary>
        internal static string ProfileImageMerging_FirstImage_NotFound {
            get {
                return ResourceManager.GetString("ProfileImageMerging.FirstImage.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình của người đứng đơn.
        /// </summary>
        internal static string ProfileImageMerging_FirstPersonUploadImage {
            get {
                return ResourceManager.GetString("ProfileImageMerging.FirstPersonUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị hình ảnh.
        /// </summary>
        internal static string ProfileImageMerging_LoadImageButton {
            get {
                return ResourceManager.GetString("ProfileImageMerging.LoadImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị ảnh từ máy.
        /// </summary>
        internal static string ProfileImageMerging_LoadLocalImageButton {
            get {
                return ResourceManager.GetString("ProfileImageMerging.LoadLocalImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị hợp đồng.
        /// </summary>
        internal static string ProfileImageMerging_LoadProfileButton {
            get {
                return ResourceManager.GetString("ProfileImageMerging.LoadProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập mã NPP!.
        /// </summary>
        internal static string ProfileImageMerging_MissingProfileId {
            get {
                return ResourceManager.GetString("ProfileImageMerging.MissingProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy hình của NPP này!.
        /// </summary>
        internal static string ProfileImageMerging_MissingProfileImage {
            get {
                return ResourceManager.GetString("ProfileImageMerging.MissingProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đủ hình ở WTA! Tiếp tục nhấn xử lý để bỏ qua và tải xuống.
        /// </summary>
        internal static string ProfileImageMerging_NotEnoughImage {
            get {
                return ResourceManager.GetString("ProfileImageMerging.NotEnoughImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng nằm ở vị trí trang thứ.
        /// </summary>
        internal static string ProfileImageMerging_ProfilePageIndex {
            get {
                return ResourceManager.GetString("ProfileImageMerging.ProfilePageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều chỉnh tỉ lệ ảnh.
        /// </summary>
        internal static string ProfileImageMerging_Scale {
            get {
                return ResourceManager.GetString("ProfileImageMerging.Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tọa độ để hình cho người chồng / vợ.
        /// </summary>
        internal static string ProfileImageMerging_SecondaryPoint {
            get {
                return ResourceManager.GetString("ProfileImageMerging.SecondaryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy ảnh của người chồng/vợ.
        /// </summary>
        internal static string ProfileImageMerging_SecondImage_NotFound {
            get {
                return ResourceManager.GetString("ProfileImageMerging.SecondImage.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình của người chồng/vợ.
        /// </summary>
        internal static string ProfileImageMerging_SecondPersonUploadImage {
            get {
                return ResourceManager.GetString("ProfileImageMerging.SecondPersonUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tọa độ để hình cho người đứng đơn.
        /// </summary>
        internal static string ProfileImageMerging_UndersignedPoint {
            get {
                return ResourceManager.GetString("ProfileImageMerging.UndersignedPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có hình gì để upload..
        /// </summary>
        internal static string ProfileImageMerging_UploadImage_NoFile {
            get {
                return ResourceManager.GetString("ProfileImageMerging.UploadImage.NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload ảnh.
        /// </summary>
        internal static string ProfileImageMerging_UploadImageButton {
            get {
                return ResourceManager.GetString("ProfileImageMerging.UploadImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã upload ảnh thành công, xin vui lòng nhấn nút &apos;Hiển thị hình ảnh&apos; để hiển thị ảnh từ máy chủ.
        /// </summary>
        internal static string ProfileImageMerging_UploadImageSuccessMessage {
            get {
                return ResourceManager.GetString("ProfileImageMerging.UploadImageSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thùng.
        /// </summary>
        internal static string ProfileScan_BoxName {
            get {
                return ResourceManager.GetString("ProfileScan.BoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string ProfileScan_Description {
            get {
                return ResourceManager.GetString("ProfileScan.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng file.
        /// </summary>
        internal static string ProfileScan_FileCount {
            get {
                return ResourceManager.GetString("ProfileScan.FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string ProfileScan_Folder {
            get {
                return ResourceManager.GetString("ProfileScan.Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả.
        /// </summary>
        internal static string ProfileScan_Result {
            get {
                return ResourceManager.GetString("ProfileScan.Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xử lý.
        /// </summary>
        internal static string ProfileScan_ScannedDate {
            get {
                return ResourceManager.GetString("ProfileScan.ScannedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả.
        /// </summary>
        internal static string ProfileScan_Search_Result {
            get {
                return ResourceManager.GetString("ProfileScan.Search.Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xử lý.
        /// </summary>
        internal static string ProfileScan_Search_ScannedDate {
            get {
                return ResourceManager.GetString("ProfileScan.Search.ScannedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        internal static string ProfileScan_Search_WarehouseId {
            get {
                return ResourceManager.GetString("ProfileScan.Search.WarehouseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm loại HS.
        /// </summary>
        internal static string ProfileType_Add {
            get {
                return ResourceManager.GetString("ProfileType.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm loại HS mới.
        /// </summary>
        internal static string ProfileType_AddNewProfileType {
            get {
                return ResourceManager.GetString("ProfileType.AddNewProfileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa loại HS của hệ thống!.
        /// </summary>
        internal static string ProfileType_CannotDeleteSystemType {
            get {
                return ResourceManager.GetString("ProfileType.CannotDeleteSystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thật sự muốn xóa loại HS này không?.
        /// </summary>
        internal static string ProfileType_ConfirmDelete {
            get {
                return ResourceManager.GetString("ProfileType.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string ProfileType_Description {
            get {
                return ResourceManager.GetString("ProfileType.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa loại HS.
        /// </summary>
        internal static string ProfileType_EditProfileType {
            get {
                return ResourceManager.GetString("ProfileType.EditProfileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi khi xóa loại HS. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string ProfileType_FailedToDelete {
            get {
                return ResourceManager.GetString("ProfileType.FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi khi lưu loại HS. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string ProfileType_FailedToSave {
            get {
                return ResourceManager.GetString("ProfileType.FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hình ảnh.
        /// </summary>
        internal static string ProfileType_Image {
            get {
                return ResourceManager.GetString("ProfileType.Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại HS.
        /// </summary>
        internal static string ProfileType_Name {
            get {
                return ResourceManager.GetString("ProfileType.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần scan.
        /// </summary>
        internal static string ProfileType_Scanned {
            get {
                return ResourceManager.GetString("ProfileType.Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số năm cần lưu.
        /// </summary>
        internal static string ProfileType_StoredYears {
            get {
                return ResourceManager.GetString("ProfileType.StoredYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm user.
        /// </summary>
        internal static string User_Add {
            get {
                return ResourceManager.GetString("User.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string User_AddNew {
            get {
                return ResourceManager.GetString("User.AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa User này không?.
        /// </summary>
        internal static string User_ConfirmDelete {
            get {
                return ResourceManager.GetString("User.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        internal static string User_Edit {
            get {
                return ResourceManager.GetString("User.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User đã tồn tại..
        /// </summary>
        internal static string User_ErrorToAddExistedUser {
            get {
                return ResourceManager.GetString("User.ErrorToAddExistedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi khi xóa user. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string User_ErrorToDeleteUser {
            get {
                return ResourceManager.GetString("User.ErrorToDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi khi cập nhật. Vui lòng liên hệ Admin!.
        /// </summary>
        internal static string User_ErrorToEditUser {
            get {
                return ResourceManager.GetString("User.ErrorToEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất ra Excel.
        /// </summary>
        internal static string User_Excel {
            get {
                return ResourceManager.GetString("User.Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string User_FullName {
            get {
                return ResourceManager.GetString("User.FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string User_Name {
            get {
                return ResourceManager.GetString("User.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        internal static string User_Role {
            get {
                return ResourceManager.GetString("User.Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa user thành công.
        /// </summary>
        internal static string User_SuccessToDeleteUser {
            get {
                return ResourceManager.GetString("User.SuccessToDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật user thành công.
        /// </summary>
        internal static string User_SuccessToEditUser {
            get {
                return ResourceManager.GetString("User.SuccessToEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        internal static string User_Warehouse {
            get {
                return ResourceManager.GetString("User.Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string Users_Password {
            get {
                return ResourceManager.GetString("Users.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        internal static string Users_Title {
            get {
                return ResourceManager.GetString("Users.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng.
        /// </summary>
        internal static string Users_UserName {
            get {
                return ResourceManager.GetString("Users.UserName", resourceCulture);
            }
        }
    }
}
